-- =============================================
-- INSERTS - USUARIO
-- =============================================
INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Ana Paula Ferreira', 'ana.ferreira@empresa.com', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'S', 'S');

INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Carlos Eduardo Lima', 'carlos.lima@empresa.com', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 'N', 'S');

INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Beatriz Souza', 'beatriz.souza@empresa.com', '2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824', 'N', 'S');

INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Rafael Oliveira', 'rafael.oliveira@empresa.com', '19a0b39a96cee4f8abd56481d1d99b0e42088107e66d65f02e5c5f1eb60e5509', 'N', 'S');

INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Fernanda Costa', 'fernanda.costa@empresa.com', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'S', 'S');

INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Marcelo Andrade', 'marcelo.andrade@empresa.com', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'N', 'N');

INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Juliana Martins', 'juliana.martins@empresa.com', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 'N', 'S');

INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Thiago Rocha', 'thiago.rocha@empresa.com', 'd4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35', 'N', 'S');

INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Camila Pereira', 'camila.pereira@empresa.com', '4e07408562bedb8b60ce05c1decbee77e4164aqe7fc2992012a4ab8e82c04be1', 'N', 'N');

INSERT INTO USUARIO (NM_USUARIO, EMAIL_USUARIO, SENHA_HASH, SN_ADMINISTRADOR, SN_ATIVO)
VALUES ('Lucas Mendes', 'lucas.mendes@empresa.com', '2c624232cdd221771294dfbb310acbc8435269acf923b73a55c97a8b7b79cae5', 'S', 'S');


-- =============================================
-- INSERTS - RESPONSAVEL
-- =============================================
INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('João Carlos Alves', 'F', '12345678901', '11987654321', 'joao.alves@email.com', 'S');

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('Tech Solutions Ltda', 'J', '12345678000195', '1132109876', 'contato@techsolutions.com.br', 'S');

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('Maria Fernanda Gomes', 'F', '98765432100', '11976543210', 'maria.gomes@email.com', 'S');

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('Equipamentos Brasil S/A', 'J', '98765432000188', '1140028922', 'suporte@equipbrasil.com.br', 'S');

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('Pedro Henrique Nunes', 'F', '11122233344', '11965432109', 'pedro.nunes@email.com', 'N');

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('Global TI Comércio Ltda', 'J', '11223344000156', '1133445566', 'comercial@globalti.com.br', 'S');

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('Aline Rodrigues Silva', 'F', '55544433322', '11954321098', 'aline.silva@email.com', 'S');

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('Inova Sistemas Eireli', 'J', '55667788000134', NULL, 'contato@inovasistemas.com.br', 'S');

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('Roberto Figueiredo', 'F', '33344455566', '11943210987', NULL, 'N');

INSERT INTO RESPONSAVEL (NM_RESPONSAVEL, TP_RESPONSAVEL, DOCUMENTO, NR_TELEFONE, EMAIL_RESPONSAVEL, SN_ATIVO)
VALUES ('Distribuidora Norte Ltda', 'J', '33445566000112', '9232109876', 'vendas@distnorte.com.br', 'S');


-- =============================================
-- INSERTS - CATEGORIA
-- =============================================
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Informática', NULL);
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Mobiliário', NULL);
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Telecomunicações', NULL);
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Computadores', 1);
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Periféricos', 1);
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Armazenamento', 1);
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Cadeiras', 2);
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Mesas', 2);
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Redes', 3);
INSERT INTO CATEGORIA (DESCRICAO, ID_MESTRE) VALUES ('Telefonia', 3);


-- =============================================
-- INSERTS - EQUIPAMENTO
-- =============================================
INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (4, 'Notebook corporativo', 2.1, 'BAR0000001', 'A', 'Dell', 'Latitude 5540');

INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (4, 'Desktop administrativo', 6.5, 'BAR0000002', 'A', 'Lenovo', 'ThinkCentre M70q');

INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (5, 'Monitor LED 27"', 4.3, 'BAR0000003', 'A', 'LG', '27MK600M');

INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (5, 'Teclado sem fio', 0.5, 'BAR0000004', 'A', 'Logitech', 'MK470');

INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (5, 'Mouse óptico USB', 0.1, 'BAR0000005', 'M', 'Microsoft', 'Wireless Mobile 1850');

INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (6, 'HD Externo 2TB', 0.3, 'BAR0000006', 'A', 'Seagate', 'Backup Plus');

INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (6, 'Servidor de arquivos NAS', 3.8, 'BAR0000007', 'A', 'QNAP', 'TS-233');

INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (9, 'Switch gerenciável 24 portas', 2.9, 'BAR0000008', 'A', 'TP-Link', 'TL-SG3424');

INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (9, 'Roteador corporativo', 0.8, 'BAR0000009', 'B', 'Cisco', 'RV340');

INSERT INTO EQUIPAMENTO (ID_CATEGORIA, DESCRICAO, PESO_KG, CD_BARRAS, TP_STATUS, DS_MARCA, DS_MODELO)
VALUES (10, 'Telefone IP', 0.6, 'BAR0000010', 'A', 'Intelbras', 'IP 8020');


-- =============================================
-- INSERTS - ENTRADA
-- =============================================
INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (1, 1, 2, DATE '2024-01-10', 'Recebimento de notebook novo para setor TI');

INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (2, 2, 4, DATE '2024-01-15', 'Desktop adquirido para setor administrativo');

INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (3, 1, 2, DATE '2024-01-15', 'Monitor para reposição do setor financeiro');

INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (4, 3, 1, DATE '2024-02-01', 'Teclado sem fio adquirido em lote');

INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (5, 3, 1, DATE '2024-02-01', 'Mouse adquirido em lote com teclado');

INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (6, 5, 6, DATE '2024-02-10', 'HD externo para backup de dados críticos');

INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (7, 5, 4, DATE '2024-03-05', 'Servidor NAS para armazenamento centralizado');

INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (8, 10, 6, DATE '2024-03-12', 'Switch para expansão da rede interna');

INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (9, 10, 8, DATE '2024-03-20', 'Roteador para filial sul');

INSERT INTO ENTRADA (ID_EQUIPAMENTO, ID_USUARIO, ID_RESPONSAVEL, DT_ENTRADA, OBSERVACAO)
VALUES (10, 7, 8, DATE '2024-04-02', 'Telefone IP para sala de reunião');


-- =============================================
-- INSERTS - SAIDA
-- =============================================
-- TP_SAIDA: E=Empréstimo, O=Outra, S=Sucateamento, D=Doação, C=Comodato, V=Venda
INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (5, 1, 2, 'E', DATE '2024-02-15', 'Empréstimo para colaborador home office');

INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (3, 3, 5, 'C', DATE '2024-02-20', 'Comodato para parceiro externo');

INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (1, 2, 1, 'E', DATE '2024-03-01', 'Empréstimo temporário para projeto externo');

INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (9, 6, 10, 'S', DATE '2024-03-25', 'Roteador com defeito irreparável, enviado para sucateamento');

INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (4, 7, 3, 'D', DATE '2024-04-05', 'Doação para escola pública parceira');

INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (6, 4, 5, 'E', DATE '2024-04-10', 'Empréstimo de HD externo para auditoria');

INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (2, 8, 7, 'V', DATE '2024-04-15', 'Venda de equipamento obsoleto para funcionário');

INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (10, 10, 8, 'C', DATE '2024-04-22', 'Comodato de telefone IP para escritório satélite');

INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (8, 9, 10, 'O', DATE '2024-05-03', 'Retirada para manutenção externa especializada');

INSERT INTO SAIDA (ID_EQUIPAMENTO, ID_RESPONSAVEL, ID_USUARIO, TP_SAIDA, DT_SAIDA, OBSERVACAO)
VALUES (7, 2, 5, 'E', DATE '2024-05-10', 'Empréstimo do servidor NAS para evento corporativo');
