-- a.  Uma consulta usando junção de mais de 2 tabelas.
-- QUANTIDADE DE ENTRADAS E SAÍDAS POR USUÁRIO
SELECT U.ID_USUARIO,
       U.NM_USUARIO,
       (SELECT COUNT(*)
          FROM ENTRADA E
         WHERE E.ID_USUARIO = U.ID_USUARIO) QTDE_ENTRADA,
       (SELECT COUNT(*)
          FROM SAIDA E
         WHERE E.ID_USUARIO = U.ID_USUARIO) QTDE_SAIDA
  FROM USUARIO U;


-- b.	Uma consulta que seja útil para a lógica de negócios usando totalização e uma função de data.
-- QUANTIDADE DE ENTRADAS NOS ÚLTIMOS 30 DIAS
SELECT COUNT(*)
  FROM SYS.ENTRADA E
 WHERE TRUNC(E.DT_ENTRADA) BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE);
 
-- QUANTIDADE DE SAÍDAS NOS ÚLTIMOS 30 DIAS
SELECT COUNT(*)
  FROM SYS.ENTRADA E
 WHERE TRUNC(E.DT_ENTRADA) BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE);
 
-- QUANTIDADE DE PRODUTOS QUE NÃO TIVERAM SAÍDA
SELECT COUNT(*)
  FROM SYS.ENTRADA E
 WHERE NOT EXISTS (SELECT 1
                     FROM SYS.SAIDA S
                    WHERE S.ID_EQUIPAMENTO = E.ID_EQUIPAMENTO);


-- c.	Uma consulta usando junção externa left join ou right join 
select E.ID_EQUIPAMENTO,
       E.DESCRICAO,
       C.ID_CATEGORIA || ' - ' || C.DESCRICAO CATEGORIA,
       ET.DT_ENTRADA,
       DOADOR.NM_RESPONSAVEL DOADOR,
       S.DT_SAIDA,
       RECEPTOR.NM_RESPONSAVEL RECEPTOR
  from SYS.EQUIPAMENTO E,
       SYS.ENTRADA ET,
       SYS.SAIDA S,
       SYS.CATEGORIA C,
       SYS.RESPONSAVEL DOADOR,
       SYS.RESPONSAVEL RECEPTOR
 WHERE E.ID_EQUIPAMENTO = ET.ID_EQUIPAMENTO
   AND E.ID_EQUIPAMENTO = S.ID_EQUIPAMENTO(+)
   AND E.ID_CATEGORIA = C.ID_CATEGORIA
   AND ET.ID_RESPONSAVEL = DOADOR.ID_RESPONSAVEL(+)
   AND S.ID_RESPONSAVEL = RECEPTOR.ID_RESPONSAVEL(+);

-- d.	Uma consulta  usando o operador de União.
-- LISTA DE TODAS AS MOVIMENTAÇÕES (ENTRADA E SAÍDA)
SELECT EQ.ID_EQUIPAMENTO,
       EQ.DESCRICAO,
       E.DT_ENTRADA,
       E.OBSERVACAO,
       'E' TP_MVTO
  FROM ENTRADA E,
       EQUIPAMENTO EQ
 WHERE E.ID_EQUIPAMENTO = EQ.ID_EQUIPAMENTO
 
 --------------------
 UNION ALL
 --------------------
 
SELECT EQ.ID_EQUIPAMENTO,
       EQ.DESCRICAO,
       S.DT_SAIDA,
       S.OBSERVACAO,
       'S' TP_MVTO
  FROM SAIDA S,
       EQUIPAMENTO EQ
 WHERE S.ID_EQUIPAMENTO = EQ.ID_EQUIPAMENTO;
 
 
-- e.	Uma consulta usando o operador Minus


-- f.	Uma consulta usando o operador de Interseção (Intersect)
